### ISSUE TITLE
Using Xrm addCustomFilter with control

### ISSUE THREAD

**Issue by mcox-supplyone** [victorsolaya/Multiselect_Records_PCF#53] opened 2024-11-01 18:48 UTC
Thanks for your excellent work with this control! It's so much more flexible and functional than the alternatives. Any thoughts about how one would go about referring to the control from the Xrm client API? I know the actual values are placed in a secondary text field, but is there a way to refer to the control itself with Xrm? I am experimenting with it now and I'll be sure to update here if I find a solution. Thanks again!

**Comment by victorsolaya** [comment] 2024-11-02 00:06
Hi, What are you trying to achieve? You have the control on a field, so you can get the value of that field and you can perform anything you want. 
What are you trying to show/get/achieve so I can help out a little bit more on this.

**Comment by mgcox2** [comment] 2024-11-02 02:29
Sorry Victor for the low-information post! There seems to be an issue with the control where it fails on create form when used with a filter. I believe my issue is a duplicate of an existing issue about that. Thank you..

**Closed as completed** 2024-11-02 09:04 UTC
